export const cows = [

{
        collar: '1989',
        ear: '819242',
        childbirth: new Date('2024-08-31'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
{
        collar: '1912',
        ear: 'n/a',
        childbirth: new Date('2024-09-01'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
{
        collar: '483',
        ear: '767506',
        childbirth: new Date('2024-09-08'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
{
        collar: '479',
        ear: '171792',
        childbirth: new Date('2024-09-08'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
{
        collar: '477',
        ear: '173213',
        childbirth: new Date('2024-09-08'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
{
        collar: '1923',
        ear: '818587',
        childbirth: new Date('2024-09-08'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },

{
        collar: '1893',
        ear: 'n/a',
        childbirth: new Date('2024-09-07'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
{
        collar: '471',
        ear: '317363',
        childbirth: new Date('2024-09-07'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
{
        collar: '1870',
        ear: 'n/a',
        childbirth: new Date('2024-09-07'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
{
        collar: '1787',
        ear: 'n/a',
        childbirth: new Date('2024-09-06'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
{
        collar: '437',
        ear: '172816',
        childbirth: new Date('2024-09-06'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
{
        collar: '432',
        ear: '170492',
        childbirth: new Date('2024-09-06'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
{
        collar: '427',
        ear: '175743',
        childbirth: new Date('2024-09-06'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },


    {
        collar: '428',
        ear: 'n/a',
        childbirth: new Date('2024-09-05'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '424',
        ear: '174753',
        childbirth: new Date('2024-09-05'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '418',
        ear: '171613',
        childbirth: new Date('2024-09-04'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '407',
        ear: '173268',
        childbirth: new Date('2024-09-04'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '393',
        ear: '765775',
        childbirth: new Date('2024-09-04'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '387',
        ear: '175099',
        childbirth: new Date('2024-09-03'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '385',
        ear: '170702',
        childbirth: new Date('2024-09-03'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '389',
        ear: '175035',
        childbirth: new Date('2024-09-02'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '276',
        ear: '766987',
        childbirth: new Date('2024-09-01'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '362',
        ear: '175664',
        childbirth: new Date('2024-09-01'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '390',
        ear: '175275',
        childbirth: new Date('2024-09-01'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '310',
        ear: '168275',
        childbirth: new Date('2024-08-29'),
        ruptures: false,
        placentaRetention: true,
        endometritis: true,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '311',
        ear: '170915',
        childbirth: new Date('2024-08-29'),
        ruptures: false,
        placentaRetention: true,
        endometritis: true,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '309',
        ear: '175169',
        childbirth: new Date('2024-08-29'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '419',
        ear: '174425',
        childbirth: new Date('2024-08-28'),
        ruptures: false,
        placentaRetention: true,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '434',
        ear: '173912',
        childbirth: new Date('2024-08-28'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '277',
        ear: '818310',
        childbirth: new Date('2024-08-25'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '368',
        ear: '170881',
        childbirth: new Date('2024-08-25'),
        ruptures: false,
        placentaRetention: false,
        endometritis: true,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '379',
        ear: '175752',
        childbirth: new Date('2024-08-24'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '357',
        ear: '174601',
        childbirth: new Date('2024-08-24'),
        ruptures: false,
        placentaRetention: false,
        endometritis: true,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '355',
        ear: '765960',
        childbirth: new Date('2024-08-23'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '345',
        ear: '175707',
        childbirth: new Date('2024-08-22'),
        ruptures: false,
        placentaRetention: false,
        endometritis: true,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '273',
        ear: '169742',
        childbirth: new Date('2024-08-22'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '261',
        ear: '172001',
        childbirth: new Date('2024-08-20'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
    {
        collar: '1942',
        ear: '913411',
        childbirth: new Date('2024-08-17'),
        ruptures: false,
        placentaRetention: false,
        endometritis: false,
        mastitis: false,
        test: true,
        enable: true,
    },
    {
        collar: '155',
        ear: '173204',
        childbirth: new Date('2024-08-16'),
        ruptures: false,
        placentaRetention: true,
        endometritis: false,
        mastitis: false,
        test: false,
        enable: true,
    },
]
